//
// AWSConfiguration.h
//
//
// Copyright 2015 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.4
#import <AWSCore/AWSCore.h>
#import <AWSCognito/AWSCognito.h>

// AMAZON COGNITO
#define AMAZON_COGNITO_REGION AWSRegionUSEast1
#define AMAZON_COGNITO_IDENTITY_POOL_ID @"us-east-1:00e260c0-8a81-4396-b7ca-85a9b7dca708"
// AMAZON MOBILE ANALYTICS
#define AMAZON_MOBILE_ANALYTICS_APP_ID @"a9e310c728a44ebcb3127b425d873bd8"
// USER FILES
#define AWS_USER_FILE_MANAGER_S3_BUCKET_NAME @"walladogaws-userfiles-mobilehub-110799703"
// USER AGENT
#define AWS_MOBILEHUB_USER_AGENT @"MobileHub aea8dac6-d2a1-4d3f-bd76-78b69e9a1473 aws-my-sample-app-ios-objc-v0.4"
